:toc:
= android-docs

= Activity

== Activity 전환시 스택 제거

``` kotlin
 val intent = Intent(this@LoginActivity, MainActivity::class.java)
intent.flags =
    Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP
startActivity(intent)
```

== 갤러리에서 이미지 가져오기
#onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)# 가 delicated되었다.

=== 액티비티에서 결과 가져오기 문서
https://developer.android.com/training/basics/intents/result?hl=ko
``` kotlin
getContent.launch("image/*")
```
``` kotlin
val getContent = registerForActivityResult(ActivityResultContracts.GetContent()) { uri: Uri? ->
    binding = MainLayoutBinding.inflate(layoutInflater)
    val rectangleView = binding.rectangleView
    uri?.let{
        var bitmap : Bitmap
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
             val source =ImageDecoder.createSource(this.getContentResolver(), uri)
            bitmap = ImageDecoder.decodeBitmap(source)
        } else {
            bitmap= MediaStore.Images.Media.getBitmap(this.contentResolver, uri)
        }
        rectangleView.drawImage(bitmap)
    }

}
```

== Navigation 사용시 Activity에서 현재 Fragment 불러오기

``` kotlin
val navHostFragment: Fragment? =
    supportFragmentManager.findFragmentById(R.id.nav_host_fragment_content_main)
val fragment = navHostFragment?.childFragmentManager?.fragments?.get(0) as IssueCreateFragment
```

== 전화걸기

=== 전화 다이얼로 이동
``` kotlin
 startActivity(Intent("android.intent.action.DIAL", Uri.parse("tel:{$번호}")))
```

=== 바로 전화 걸기
``` kotlin
 startActivity(Intent("android.intent.action.CALL", Uri.parse("tel:{$번호}")))
```
= View

== ScrollView => NestedScorollView
공부예정

== ViewModel

=== ViewModel의 이점

* UI 상태를 유지할 수 있습니다.
* 비즈니스 로직에 대한 액세스 권한을 제공합니다.

== MVVM 패턴
MVVM의 관점에서 뷰모델은 View로부터 독립적이며 View가 필요로 하는 데이터만 소유한다.

MVVM 관점의 뷰모델 구현 시 AAC ViewModel을 쓰면 좋다.

=== ViewModel

= Component
== 캘린더에서 날짜 선택

``` kotlin
 val cal = Calendar.getInstance()
 val data = DatePickerDialog.OnDateSetListener { view, year, month, day ->
     binding.birthSelectButton.text = "${year}-${month + 1}-${day}"
 }
 DatePickerDialog(
     this,
     data,
     cal.get(Calendar.YEAR),
     cal.get(Calendar.MONTH),
     cal.get(Calendar.DAY_OF_MONTH)
 ).show()
```

== Toast 메시지 띄우기

``` kotlin
            Toast.makeText(context,"전송할 메시지", Toast.LENGTH_LONG).show()

```

== editText Text 변화감지

```kotlin
        editTextId.addTextChangedListener(
            @SuppressLint("RestrictedApi")
            object : TextWatcherAdapter() {
                override fun onTextChanged(id: CharSequence, start: Int, before: Int, count: Int) {
                    //변화가 감지되면 실행될 동작
                }
            }


        )
```

= Network

== Retrofit
Retrofit 사용 POST 매핑 예제
``` kotlin
interface LoginService {
    @POST("/login")
    fun login(
        @Body loginRequest : LoginRequest,
    ) : Call<LoginResponse>

    companion object{
        private const val BASE_URL = "BaseURL"
        private val gson =
            GsonBuilder()
                .setLenient()
                .create()

        fun create() : LoginService {
            return Retrofit.Builder()
                .baseUrl(BASE_URL)
                .client(OkHttpClient.Builder().build())
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build()
                .create(LoginService::class.java)
        }
    }
}
```
Retrofit 사용 GET 매핑 예제
``` kotlin
interface LoginService {
    @GET("/login")
    fun login(
        @Query("userId") val id : String,
        @Query("name") val name : String,
    ) : Call<LoginResponse>

   '''
}
```


= Permission

== workflow
1. manifest에 권한선언
2. 특정 런타임 권한이 필요하도록 UX 설계
3. 권한이 필요한 경우에만 요청
4. 사용자가 이미 권한을 부여했는지 확인
5. 사용자에게 권한을 부여해야하는 이유 설명
6. 런타임 권한 요청
7. 사용자 응답결과 확인
8. 권한허용을 거절한 경우 해당 기능 제외후 앱 사용하도록 만들어야함.

= UI

== 키보드 내리기

액티비티에 dispatchTouchEvent를 override해서 현재 focus가 되어있는 곳이 아닌 곳을 선택하면 키보드를 내리고 focus를 취소한다.

``` kotlin
    override fun dispatchTouchEvent(ev: MotionEvent?): Boolean {
        val focusView = currentFocus
        if (focusView != null && ev != null) {
            val rect = Rect()
            focusView.getGlobalVisibleRect(rect)
            val x = ev.x.toInt()
            val y = ev.y.toInt()

            if (!rect.contains(x, y)) {
                val imm = getSystemService(INPUT_METHOD_SERVICE) as InputMethodManager
                imm.hideSoftInputFromWindow(focusView.windowToken, 0)
                focusView.clearFocus()
            }
        }
        return super.dispatchTouchEvent(ev)
    }
```

== Canvas

=== text 범위 구하기

getTextBounds를 사용해서 text 사이즈에 따른 테두리 를 얻을 수 있다.
x,y 좌표로 구하기 위해 left, right, bottom, top을 따로 구했다.

```kotlin
val textBounds = Rect()
val textPaint = Paint()
textPaint.textSize = item.size.width
textPaint.getTextBounds(item.text, 0, item.text.length, textBounds)

val left = item.point.x
val top = item.point.y
val right = left + textBounds.right.toFloat()
val bottom = top + textBounds.top.toFloat()
if ((x in left..right) and (y in bottom..top)) return index
```

== DropDown TextEdit 만들기

```xml
    <com.google.android.material.textfield.TextInputLayout
        ...
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu"
        >

        <AutoCompleteTextView
            ...
            />

    </com.google.android.material.textfield.TextInputLayout>


```
TextInputLayout에 style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox.ExposedDropdownMenu" 속성을 넣고 내부에 AutoCompleteTextView를 사용한다.

---

== 스와이프 새로고침
SwipeRefreshLayout은 단일 ListView 또는 GridView 하위 요소만 지원한다.
```kotlin
<android.support.v4.widget.SwipeRefreshLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/swiperefresh"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <ListView
            android:id="@android:id/list"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </android.support.v4.widget.SwipeRefreshLayout>
```
이렇게 하면 스와이프를 했을 때, onRefresh()가 호출된다.
onRefresh()안에 동작을 구현한다.
데이터 업데이트가 완료되면 setRefreshing(false)을 호출한다.

= Jetpack

== Jetpack Navigation
Navigation graph를 사용해서 시각화된 정보를 이용해서 navigation 구현 가능.

== Navigation 가능 대상
1. Activity
2. Fragment
3. Dialog


= ERROR

== Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $

retrofit에서 배열명이 없는 배열이 response로 올 경우 발생한다.
``` kotlin
@GET("~")
Call<List<item>> getData()
```
다음과 같이 response를 List형태로 받으면 된다.

[참고] https://velog.io/@steelzoo/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%A0%88%ED%8A%B8%EB%A1%9C%ED%95%8F-JSON-%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B0%80-%EB%B0%B0%EC%97%B4%EB%A7%8C-%EC%9E%88%EC%9D%84%EB%95%8C%EC%97%90%EB%9F%ACExpected-BEGINOBJECT-but-was-BEGINARRAY-at-line-1-column-2-path

== android.os.NetworkOnMainThreadException
네트워크 API를 직접 사용하였을 때 발생하는 오류
코루틴을 사용해서 처리해야한다.


=== viewModel databind 사용시 잘했는데 안나올때 확인할 것

lifecycleOwner와 viewModel 설정!!

``` kotlin
val binding: YourLayoutBinding = DataBindingUtil.setContentView(this, R.layout.your_layout)
binding.viewModel = ViewModelProvider(this).get(MyViewModel::class.java)
binding.lifecycleOwner = this
```

== Cannot access database on the main thread since it may potentially lock the UI for a long period of time.

```kotlin
MyApp.database =  Room.databaseBuilder(this, AppDatabase::class.java, "MyDatabase").allowMainThreadQueries().build()
```

= CS

== SOLID

1. SRP(단일 책임원칙)

클래스가 단일한 책임만 가지도록 해서 응집도가 높게!!,  결합도 관점에서도 결합도가 낮도록!

2. Open-Closed Principle(OCP)

소프트웨어 개체는 확장에 대해 열려 있어야하고 수정에 대해서는 닫혀 있어야한다. 즉, 기능을 추가하고자 할때는 수정없이도 일어나야한다.

''' 나머지 추가 예정

