:toc:
= android-docs

= Activity

== 갤러리에서 이미지 가져오기
#onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)# 가 delicated되었다.

=== 활동에서 결과 가져오기 문서
https://developer.android.com/training/basics/intents/result?hl=ko
``` kotlin
getContent.launch("image/*")
```
``` kotlin
val getContent = registerForActivityResult(ActivityResultContracts.GetContent()) { uri: Uri? ->
    binding = MainLayoutBinding.inflate(layoutInflater)
    val rectangleView = binding.rectangleView
    uri?.let{
        var bitmap : Bitmap
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
             val source =ImageDecoder.createSource(this.getContentResolver(), uri)
            bitmap = ImageDecoder.decodeBitmap(source)
        } else {
            bitmap= MediaStore.Images.Media.getBitmap(this.contentResolver, uri)
        }
        rectangleView.drawImage(bitmap)
    }

}
```

= View

== ScrollView => NestedScorollView
공부예정

== ViewModel

=== ViewModel의 이점

* UI 상태를 유지할 수 있습니다.
* 비즈니스 로직에 대한 액세스 권한을 제공합니다.

== MVVM 패턴
MVVM의 관점에서 뷰모델은 View로부터 독립적이며 View가 필요로 하는 데이터만 소유한다.

MVVM 관점의 뷰모델 구현 시 AAC ViewModel을 쓰면 좋다.

=== ViewModel

= Component

== Toast 메시지 띄우기

``` kotlin
            Toast.makeText(context,"전송할 메시지", Toast.LENGTH_LONG).show()

```


= Permission

== workflow
1. manifest에 권한선언
2. 특정 런타임 권한이 필요하도록 UX 설계
3. 권한이 필요한 경우에만 요청
4. 사용자가 이미 권한을 부여했는지 확인
5. 사용자에게 권한을 부여해야하는 이유 설명
6. 런타임 권한 요청
7. 사용자 응답결과 확인
8. 권한허용을 거절한 경우 해당 기능 제외후 앱 사용하도록 만들어야함.

= UI

== 키보드 내리기

액티비티에 dispatchTouchEvent를 override해서 현재 focus가 되어있는 곳이 아닌 곳을 선택하면 키보드를 내리고 focus를 취소한다.

``` kotlin
    override fun dispatchTouchEvent(ev: MotionEvent?): Boolean {
        val focusView = currentFocus
        if (focusView != null && ev != null) {
            val rect = Rect()
            focusView.getGlobalVisibleRect(rect)
            val x = ev.x.toInt()
            val y = ev.y.toInt()

            if (!rect.contains(x, y)) {
                val imm = getSystemService(INPUT_METHOD_SERVICE) as InputMethodManager
                imm.hideSoftInputFromWindow(focusView.windowToken, 0)
                focusView.clearFocus()
            }
        }
        return super.dispatchTouchEvent(ev)
    }
```

== Canvas

=== text 범위 구하기

getTextBounds를 사용해서 text 사이즈에 따른 테두리 를 얻을 수 있다.
x,y 좌표로 구하기 위해 left, right, bottom, top을 따로 구했다.

```kotlin
val textBounds = Rect()
val textPaint = Paint()
textPaint.textSize = item.size.width
textPaint.getTextBounds(item.text, 0, item.text.length, textBounds)

val left = item.point.x
val top = item.point.y
val right = left + textBounds.right.toFloat()
val bottom = top + textBounds.top.toFloat()
if ((x in left..right) and (y in bottom..top)) return index
```

= Jetpack

== Jetpack Navigation
Navigation graph를 사용해서 시각화된 정보를 이용해서 navigation 구현 가능.

== Navigation 가능 대상
1. Activity
2. Fragment
3. Dialog
